### ISSUE TITLE
Could you add the comparison of last two opened document tabs?

### ISSUE THREAD

**Issue by ycherkes** [heku/Kool.VsDiff#7]
I think it will be very useful to have an option to compare two last opened document tabs like it's done in a Compare plugin of notepad++.
Because it's not necessary that the opened file is a part of the solution. It can be externally opened in Visual Studio.
Is that possible?

**Comment by heku** [comment]
I'm not sure if it's possible to detect what tabs are last opened twos, I need investigate. If this is possible, where to display the 'Compare ...' context menu?

**Comment by ycherkes** [comment]
This menu item can be added not to the context menu but rather to the main "File" menu.

**Comment by ycherkes** [comment]
The code from the [TidyTabs](https://github.com/davemckeown/TidyTabs-VisualStudio/blob/master/TidyTabs/TidyTabsPackage.cs) extension can help to figure out the tab opening order.

**Comment by heku** [comment]
Thanks, I will take a look.

**Comment by ycherkes** [comment]
Hi @heku,
I think  it can be even better to add the context menu "Compare to right tab" and "Compare to left tab". Example can be found here https://github.com/billpratt/CloseTabsToRight.
What do you think?

**Comment by heku** [comment]
This way, user always need move the tab to compare to eithor left or right of current tab firstly, I think this is not more friendly than current approcah - copy the content then 'Compare with Clipboard', let's think again to find if there's any better way.

**Comment by ycherkes** [comment]
Let me describe the root of my problem: I have an extension - [Object Dumper](https://marketplace.visualstudio.com/items?itemName=YevhenCherkes.YellowFlavorObjectDumper). It creates the dumps of debugged objects and opens them as separate documents. Those documents are not part of the solution. But I would like to have the ability to compare two of the generated documents. The 'Compare with Clipboard' approach won't work in this case.

**Comment by ycherkes** [comment]
I know that the "Miscellaneous Files" can be shown in Solution Explorer, but this option is disabled by default, and not so many people know about that:

![image](https://user-images.githubusercontent.com/13467759/170815707-d51e8c51-8a5c-4fc7-bd7e-c2cd124bd9c4.png)

![image](https://user-images.githubusercontent.com/13467759/170815851-14a06541-505a-4954-838b-8792eb3bff1a.png)

**Comment by ycherkes** [comment]
Also, there is an issue because both of them are temporary unsaved files.

![ComparisonIssue](https://user-images.githubusercontent.com/13467759/170816411-824efeb4-d367-4f09-86ad-45bb842ea905.gif)

Please pay attention to file names in a comparison window:

![274](https://user-images.githubusercontent.com/13467759/170823237-b2d509fa-9a56-4aae-820a-260d618524c0.png)

**Comment by heku** [comment]
I see the file name issue, I think I need to look up some vsix docs to fix it.

**Comment by ycherkes** [comment]
Yup and not file name issue only - it takes the document's text for an active item from the document, but for the second tries to get it from the file, but the file is empty. That's why I'm asking about the comparison of the two tabs.

**Comment by heku** [comment]
Hi @ycherkes , after a little research, I think we need update our code together to resolve this problem. 

Currently this extension supports both VS's builtin file compare service and external tools, these are all based on physical files, i.e. the core API is something like `diff(file1, file2)`.

So, if  the physical file contains nothing but VS hold its unsaved changes, then it won't work as your expect, but it looks reasonable to me, for external tools, it's reasonable that they don't know these unsaved content. 

And from my test, although VS's builtin diff service take two files path as parameters, seems VS treats them differently, VS loads left file content from physical file, but loads right file with cache (VS unsaved content), that's why left side is empty in your last screenshot.

I also checked your extension's code, looks like you can change this line
https://github.com/ycherkes/ObjectDumper/blob/main/src/ObjectDumper/DumpAsCommandHelper.cs#L140
to
```csharp
newDocument.Save();
```

Then VS will save the content to pyhsical temp file too, this should fix the issue you have.

Regarding the file name issue, I'll enhance the code, pass the display name to diff tool.

**Comment by ycherkes** [comment]
Hey @heku,
Thanks a lot for your research.
I've already fixed the document saving issue - [bbf47f505b1af57b89b61f985297cca518fcc34b](https://github.com/ycherkes/ObjectDumper/commit/bbf47f505b1af57b89b61f985297cca518fcc34b)
Thanks a lot, it's amazing :)

**Comment by heku** [comment]
@ycherkes np, thx for the feedback too.

**Comment by heku** [comment]
Hi @ycherkes, the file name issue fixed, could you please test the latest dev branch build https://dev.azure.com/heku/d55bc262-1377-4ae3-9410-4c98cfa53de8/_apis/build/builds/149/artifacts?artifactName=drop&api-version=7.0&%24format=zip
Thanks.

**Comment by ycherkes** [comment]
Hi @heku, I've tested a VsDiff.2022.vsix, all works fine!
Thank you!

**Comment by heku** [comment]
@ycherkes Thanks.
